## ======================================================================
## resource_types
## ======================================================================
resource_types:
  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

## ======================================================================
## resources
## ======================================================================
resources:
  ## Image Resources
  - name: gpdb6-centos6-build
    type: docker-image
    source:
      repository: pivotaldata/gpdb6-centos6-build
      tag: 'latest'

  - name: gpdb6-centos7-build
    type: docker-image
    source:
      repository: pivotaldata/gpdb6-centos7-build
      tag: 'latest'

  - name: gpdb6-ubuntu18.04-build
    type: docker-image
    source:
      repository: pivotaldata/gpdb6-ubuntu18.04-build
      tag: 'latest'

  - name: gpdb_src
    type: git
    source:
      branch: {{gpdb-git-branch}}
      uri: {{gpdb-git-remote}}
      # tag_filter: 6.*

  ## gp internal artifacts
  - name: python-centos6
    type: gcs
    source:
      bucket: ((pivotal-gp-internal-artifacts-gcs-bucket))
      json_key: ((gcs-key))
      versioned_file: centos6/python-2.7.12.tar.gz

  - name: python-centos7
    type: gcs
    source:
      bucket: ((pivotal-gp-internal-artifacts-gcs-bucket))
      json_key: ((gcs-key))
      versioned_file: centos7/python-2.7.12.tar.gz

  - name: python-ubuntu18.04
    type: gcs
    source:
      bucket: gp-internal-artifacts
      json_key: ((gcs-key))
      versioned_file: ubuntu18.04/python-2.7.12.tar.gz

## ======================================================================
## JOBS JOBS JOBS
## ======================================================================
jobs:
  - name: compile_gpdb_centos6
    plan:
      - aggregate:
          - get: gpdb_src
            trigger: true
          - get: gpdb6-centos6-build
          - get: python-tarball
            resource: python-centos6
      - task: compile_gpdb
        file: gpdb_src/concourse/tasks/compile_gpdb_oss.yml
        image: gpdb6-centos6-build
  - name: compile_gpdb_centos7
    plan:
      - aggregate:
          - get: gpdb_src
            trigger: true
          - get: gpdb6-centos7-build
          - get: python-tarball
            resource: python-centos7
      - task: compile_gpdb
        image: gpdb6-centos7-build
        file: gpdb_src/concourse/tasks/compile_gpdb_oss.yml

  - name: compile_gpdb_ubuntu18.04
    plan:
      - aggregate:
          - get: gpdb_src
            trigger: true
          - get: gpdb6-ubuntu18.04-build
          - get: python-tarball
            resource: python-ubuntu18.04
      - task: compile_gpdb
        image: gpdb6-ubuntu18.04-build
        file: gpdb_src/concourse/tasks/compile_gpdb_oss.yml